# 배운 것들

## Nest.js HTTP Exception

원래 HttpException의 constructor는 string인 message를 받는다.
그래서 항상 Guard 레벨에서 에러를 낼 때, throw new DuoGameHttpException('User does not exist') 이런 식으로 constructor를 string 타입으로 줘서 HTTP Status code가 400번 때 였다. 근데 Unity 클라이언트는 400번 상태 코드를 받으면 무조건 에러로 간주해서 예외처리가 힘들어서 200번 코드를 주어야했다. 그래서 가드레벨에서 예외 처리하는 것을 포기해야하나 했는데

HttpException definition을 찾아보니 object 타입도 오버로딩하고 있었다. 그래서 object JSON을 response body로 보내준다.

예시는 아래와 같다.

```typescript
import { FORBIDDEN } from "@nestjs/common";

export class DuoGameHttpException extends HttpException {
  constructor(
    message: string | object,
    httpStatus: HttpStatus = HttpStatus.FORBIDDEN
  ) {
    super(message, httpStatus);
  }
}

export class ServerCheckService {
  public versionCheck() {
    const serverVersions = await axios.get("s3://gameduo/serverVersions.net");
    if (serverVersions == null)
      throw new DuoGameHttpException(
        {
          isService: false,
          bundle: serverVersions.bundle, // JSON
        },
        200
      );

    if (!serverVersions.isService) {
      throw new DuoGameHttpException(
        {
          isService: false,
          bundle: serverVersions.bundle, // JSON
        },
        200
      );
    }
  }
}
```

Error를 throw 할 때, 클라이언트가 받을 response body

```JSON
    {
        "isService": false,
        "bundle": {
            "stage": 123,
            "gold": 100000,
            "monster_level": 100
        }
    }
```
